apiVersion: v1
kind: Service
metadata:
  name: lfc-bo-#SERVICE_CODE#-cluster
spec:
  selector:
    app: lfc-bo-#SERVICE_CODE#
  ports:
    - port: #SERVICE_PORT#1
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lfc-bo-#SERVICE_CODE#-lb
spec:
  selector:
    app: lfc-bo-#SERVICE_CODE#
  ports:
    - port: #SERVICE_PORT#0
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lfc-bo-#SERVICE_CODE#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lfc-bo-#SERVICE_CODE#
  template:
    metadata:
      labels:
        app: lfc-bo-#SERVICE_CODE#
    spec:     # pod spec                  
      containers: 
      - name: lfc-bo 
        image: images.mobiguider.cloud/bo-nodejs:latest
        env:
        - name: MONGO_URL
          value: mongodb://mongo-#SERVICE_CODE#:27017/dev
        - name: MINIO_ACCESS_KEY
          value: mykey
        - name: MINIO_SECRET_KEY
          value: mysecret
        - name: MINIO_HOST
          value: minio
        ports:
        - containerPort: 3000
      imagePullSecrets:
          - name: regcred            