apiVersion: v1
kind: Service
metadata:
  name: lfc-bo-marta
spec:
  selector:
    app: lfc-bo-marta
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lfc-bo-marta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lfc-bo-marta
  template:
    metadata:
      labels:
        app: lfc-bo-marta
    spec:
      containers:
        - name: lfc-bo-marta
          image: bwalia/lfc-bo:1.0.3
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: mykey
            - name: MINIO_SECRET_KEY
              value: mysecret
            - name: MINIO_HOST
              value: minio
          imagePullPolicy: Always
