apiVersion: v1
kind: Service
metadata:
  name: minio-marta-nodeport
  namespace: default
spec:
  type: NodePort 
  ports:
  - port: 9000
    targetPort: 9000
    name: minio
  selector:
    app: minio-marta